### ISSUE TITLE
Mimikatz Cannot Extract the Dump Generated

### ISSUE THREAD

**Issue by bizzworld2030** [tihanyin/PSSW100AVB#7]
There's an error on the dump generated for Windows 10, 2012 and 2016. Mimikatz won't extract it. Gives an error "Minidump without SystemInfoStream (?)" and "ERROR kuhl_m_sekurlsa_acquireLSA ; Modules Informations"

**Comment by tihanyin** [comment]
Hi ,
Thanks for your feedback. I think the issue is related to some settings, not the generated dump file.
I also tested with the latest Win10 Pro (Defender enabled) and worked for me.

![image](https://user-images.githubusercontent.com/62064939/160683049-b75e11f1-f676-4db2-bfac-ddea67a02f5f.png)

**Comment by tihanyin** [comment]
Hi ,
Thanks for your feedback. I think the issue is related to some settings, not the generated dump file.
I also tested with the latest Win10 Pro (Defender enabled) and worked for me.
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/62064939/160690038-71438446-ff46-41af-8728-4b0a6ae1d5b5.png">
